name: all-lints

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@master
        with:
          python-root-list: "tests"
          use-mypy: true
          use-black: true
          use-isort: true
          use-pylint: true
          use-flake8: true
          use-pycodestyle: true
